### ISSUE TITLE
The audio icon is cut off on Search results page on Edge on ODE 377

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#100]
### Issue description
*Description of the issue*
The audio icon is cut off on Search results page on Edge when zoomed in at 100%

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to ODE 377 on Edge
2. Perform search with "cancer" 
3. The audio icon is cut-off in the dictionary definition 
4. Repeat step 1 and 2 with "lynch syndrome"
5. The audio icon is cut-off in the best bet dictionary definition 

### What's the expected result?
- The audio icon should not appear as cut-off in the dictionary definition and best bet dictionary definition

### What's the actual result?
- The audio icon appears as cut-off in the dictionary definition and best bet dictionary definition

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/90450698-484f9200-e0b8-11ea-939a-3983fc67c1b0.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
This issue has been fixed with Redesign MVP1 release.
