### ISSUE TITLE
Drop-down in microsites are not getting Prod drop-down background color

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#102]
### Issue description
*Description of the issue*

On microsites, we need to update the Drop-down background color, Pager colors, Active state color on Pagers and Hover color on Search results page.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://www.cancer.gov/pediatric-adult-rare-tumor
2. Perform search with "cancer"
3. Repeat same step with https://www.cancer.gov/rare-brain-spine-tumor, https://www.cancer.gov/rare-brain-spine-tumor/espanol , https://www.cancer.gov/nano and https://dceg.cancer.gov/nano

### What's the expected result?
- The Drop-down background color, Pager colors, Active state color on Pagers and Hover color on Search results page should match the respective microsite theme requirement.

### What's the actual result?
- The Drop-down background color, Pager colors, Active state color on Pagers and Hover color on Search results page are not in sync with the requirement of respective microsites theme color.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/90569657-4222e980-e17c-11ea-8db7-7576a7cdb4b3.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
Closing this ticket, as microsites no longer have their own themes with Redesign MVP1.
