### ISSUE TITLE
Sitewide Search Should not include Robots meta tag

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/sitewide-search-app#109]
### Issue description
Drupal outputs this tag, and this must be tracked by Drupal so that it is NOT included in the sitemap.xml.  Since the application does not change the value of this, there is no reason to output it, and in fact it should not in order to avoid sending Google or other search engines mixed signals.  

> **ESTIMATE** TBD

**Comment by sarinapadilla** [comment]
This issue was fixed with [this commit](https://github.com/NCIOCPL/sitewide-search-app/commit/aa59703684d4c662c405cc74decef7e91686d4dc) so closing this ticket!
