### ISSUE TITLE
The drop-down button on Site Wide Search results page/CTS View Page Location accordion does not get blue background color on Edge and FF

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#128]
### Issue description
The drop-down button on Site Wide Search results page does not get blue background color on Edge and FF on Prod.
The drop-down button for "States" on CTS Trial Description page under Location accordion has also this issue on Prod.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1.  Go to Cancer.gov on Edge and FF
2. Perform search with "cancer"
3. Scroll down until you see the drop-down button
4. Change the page number to 50 from the drop-down button
5. See that the background color is appearing grey (not blue) on Edge and FF 
6.  Go to https://www.cancer.gov/about-cancer/treatment/clinical-trials/search/v?id=NCI-2014-01507&loc=0&rl=1 on Edge and FF
7. Expand the Locations & Contacts accordion
8. Click the "State" drop-down
9. See that the background color is appearing grey (not blue) on Edge and FF 

### What's the expected result?
- The drop-down button on Site Wide Search results page should get blue background color (same color as we see on Chrome) on all browsers

### What's the actual result?
- The drop-down button on Site Wide Search results page does not get blue background color on Edge and FF

### Additional details / screenshot
![image](https://user-images.githubusercontent.com/28455973/165578195-73e2a791-97ec-470b-90c9-9fda31db8c95.png)
![image](https://user-images.githubusercontent.com/28455973/165578331-e2c1928f-ac37-4373-8fcb-eb55d300b322.png)
![image](https://user-images.githubusercontent.com/28455973/165578494-e3fd86ef-fc4f-404e-b7b8-c99ae6447df5.png)
![image](https://user-images.githubusercontent.com/28455973/165600880-6fba78bf-a437-4ecc-bafc-634c748c0089.png)

### Related Tickets
* Issue #9999
* Issue #9999

cc: @VictoriaSunNIH , @mworrest 
@sarinapadilla , FYI, The drop-down button for "States" on CTS Trial Description page under Location accordion has also this issue on Prod.

**Comment by sarinapadilla** [comment]
The native colors for dropdowns are different between browsers and operating systems. Right now, Edge is the only browser displaying a grey background - Chrome, FF, and Safari are all showing blue. Closing this ticket as we do not currently have styling for those specific dropdowns.
