### ISSUE TITLE
20 or 50 display options dont work on mobile

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/sitewide-search-app#33]
### Issue description
When on an actual mobile device, the option to change from 20 results to display 50 results doesn't work.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  On safari or chrome on an actual mobile device (not a page resized), switch the options to show 50
2. Note that the page refreshes, but still only shows 20

### What's the expected result?
The page should refresh to show 50 when selected.

### What's the actual result?
The page refreshes but still shows 20.

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by amydugan** [comment]
Closed by PR #18
