### ISSUE TITLE
URL in results not wrapping correctly on mobile

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/sitewide-search-app#35]
### Issue description
On mobile, the URL is not wrapping correctly, causing it to extend off the screen.  

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/sitewide-search-app/pr-18/?swkeyword=myeloproliferative on mobile (testing in Safari on iPhone 11)
2. Look at the URL for the PDF in this result: "Surgery Codes Hematopoietic/Reticuloendothelial/Immunoproliferative/Myeloproliferative Disease"
3. See it goes off the page

VERIFIED ON ANOTHER PAGE:
1. Go to https://react-app-dev.cancer.gov/sitewide-search-app/pr-18/?swkeyword=colorectal-cancer&page=2&pageunit=20&Offset=41 on mobile (testing in Safari on iPhone 11)
2. Look at the URL for this result: "Colonoscopy Reduces Risk of Death from Colorectal Cancer in High-Risk Patients"
3. See it goes off the page

### What's the expected result?
- Like prod, the line breaks earlier on so that the text doesn't extend off the page.

### What's the actual result?
- The line doesn't break so the text goes off the page.

### Additional details / screenshot
![Screen Shot 2020-07-29 at 3 38 56 PM](https://user-images.githubusercontent.com/4921685/88845397-141c3c00-d1b2-11ea-8fa1-b4ac1b38f668.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by VictoriaSunNIH** [comment]
@karlikpj - while the URL wraps, the content in the example for myeloproliferative still causes the page to extend off the screen unfortunately
