### ISSUE TITLE
Lower the margin on the right side of search results on mobile

### ISSUE THREAD

**Issue by mworrest** [NCIOCPL/sitewide-search-app#60]
### Issue description
This is not a show stopper. There seems to be more margin on the right side of the page than the left on mobile.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to https://react-app-dev.cancer.gov/sitewide-search-app/demo/?cfg=0&swkeyword=lynch+syndrome&page=1&pageunit=20&Offset=0 on phone
2. See you can scroll right to see extra margin

### What's the expected result?
- There should be equal margin on either side of the page

### What's the actual result?
- There is more margin on the right side

### Additional details / screenshot
<img width="401" alt="Screen Shot 2020-08-06 at 11 41 51 AM" src="https://user-images.githubusercontent.com/4921685/89552205-d898f780-d7d9-11ea-9520-80caf8e445dc.png">

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blilianyu** [comment]
Looks good!
