### ISSUE TITLE
IE issues on the Search Results Page

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#63]
### Issue description
*Description of the issue*
Some IE issues on the Search Results Page
- The drop-down buttons are not appearing correctly
- The show/hide button for More Info is getting cut-off
- The font style does not match Prod
- On clicking the drop-down  button the drop-down menu does not appear correctly 
- Definitions for Best Bets not appearing on the right side of the page, it is appearing below the Best Bets text ( This has been resolved by #57 ) 

> **ESTIMATE** 20

### Steps to reproduce the issue

1. On IE, go to  http://ncigovcdode377.prod.acquia-sites.com/search/results?swKeyword=cancer
2. Scroll all the way down until the "Show # results per page" drop-down is visible.
3. Also, scroll-up and notice that the "Show full definition" button is cut-off. Click the  "Show full definition" button and the "Hide full definition" button appears cut-off.
4. The font style in the search results page is totally different on ODE
5. On clicking the drop-down  button the drop-down menu does not appear correctly 
6. Search with "mantle cell lymphoma" 

### What's the expected result?
- The drop-down buttons should appear correctly on Search Results page
- The show/hide button for More Info should not get cut-off on Search Results page
- The font style should match Prod on Search Results page
- On clicking the drop-down  button the drop-down menu should appear correctly 
- Definitions for Best Bets should appear on the right side of the page

### What's the actual result?
- The drop-down buttons are not appear correctly on Search Results page
- The show/hide button for More Info should is getting cut-off on Search Results page
- The font style does not match Prod on Search Results page
- Definitions for Best Bets not appearing on the right side of the page, it is appearing below the Best Bets text

### Additional details / screenshot
- ![Screenshot]

![image](https://user-images.githubusercontent.com/28455973/89591615-a1960680-d818-11ea-875c-950f594bc752.png)

![image](https://user-images.githubusercontent.com/28455973/89591779-110bf600-d819-11ea-89a6-0d8267b0625c.png)

![image](https://user-images.githubusercontent.com/28455973/89591931-6a742500-d819-11ea-9e6e-ddd038056fbe.png)

![image](https://user-images.githubusercontent.com/28455973/89592985-00a94a80-d81c-11ea-916c-07aefe0f7dea.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by karlikpj** [comment]
@arcepaul looks like it's not getting the font for the entire site - I don't see the correct font in the menu, or footer in the screen shots. Is there a font file/scss/path off that I am unaware of?

**Comment by alinai** [comment]
On IE,  https://react-app-dev.cancer.gov/sitewide-search-app/pr-66?swkeyword=cancer,
The drop-down buttons are appearing correctly (verified the appearance with @Lindsay Burack and @Lilian)
The show/hide button for More Info is looking good
The font style DOES NOT match Prod
On clicking the drop-down button the drop-down menu DOES NOT appear correctly
Definitions for Best Bets appearing correctly  on the right side of the page but the audio icon gets cut-off and huge white space between the term and pronunciation in the definition for best bets but this spacing issue exists on chrome too on ODE 377
