### ISSUE TITLE
Issues noticed while testing on different browsers 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#71]
### Issue description
*Description of the issue*
Issues noticed on 377 and react dev while testing in different browsers (FF, Chrome, Edge, IE) 

> **ESTIMATE** 20

### Issues:
1.  Site Wide Search is not working on Edge.
2. Pager appearing on Search results page for term <=20
3. "Show # of results per page" has different text in Spanish version (verify requirement) 
4. "Show # of results per page"  is appearing in camel-case in 377 ( verify requirement)
5. Searching for '/' returns error page.
6. ODE displays breadcrumb in Spanish version of Search results page
7. The issue with no results found page on ODE (displays Results 0-0 of 0 for: achoo and Results 0-0 of 0)
8. The spacing issue on the definitions (between the term and the phonetic spelling). This spacing should be tighter.
9.  At 630px and lower, the audio icon wraps to the next line even if we have enough space on the right in all browsers.
10. At 640px and lower, the drop-down box appears too wide.

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by arcepaul** [comment]
Let's break this one up into separate bug tickets if necessary.

**Comment by alinai** [comment]
1. Site Wide Search is not working on Edge. (Works on react-dev, need to test on ODE).
Looks good on ODE
2. Pager appearing on Search results page for term <=20 (Fixed on react dev)
Looks good on ODE
3. "Show # of results per page" has different text in Spanish version (verify requirement) ( Fixed on react dev)
Looks good on ODE
4. "Show # of results per page" is appearing in camel-case in 377 ( verify requirement) ( Fixed on react dev)
Looks good on ODE
5. Searching for '/' returns error page. (#75)
6. ODE displays breadcrumb in Spanish version of Search results page (https://github.com/NCIOCPL/cgov-digital-platform/issues/2883)
7. The issue with no results found page on ODE (displays Results 0-0 of 0 for: achoo and Results 0-0 of 0) (#72)
Looks good on ODE
8. The spacing issue on the definitions (between the term and the phonetic spelling). This spacing should be tighter. (#76)
9. At 630px and lower, the audio icon wraps to the next line even if we have enough space on the right in all browsers. (Fixed on react dev) (#74)
@blilianyu  commented on #74 
10. At 640px and lower, the drop-down box appears too wide.( Fixed on react dev)
Looks good on ODE
