### ISSUE TITLE
The audio icon wrapping issue for longer terms at smaller break points

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#74]
### Issue description
*Description of the issue*
We are noticing issues with wrapping  of audio icons for longer terms such as "accelerated phase chronic myelogenous leukemia".  This is happening in all browsers.
> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Perform SWS with "accelerated phase chronic myelogenous leukemia"

### What's the expected result?
The wrapping of audio icons should match with Prod at  smaller breakpoints.

### What's the actual result?
-The wrapping of audio icons does not match with Prod at  smaller breakpoints.

### Additional details / screenshot

![image](https://user-images.githubusercontent.com/28455973/89944708-42f0d400-dbee-11ea-9789-8079228990ab.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blilianyu** [comment]
Pronunciation should wrap and not break onto the next line below the speaker icon starting at 513 to 320.

![513](https://user-images.githubusercontent.com/51677926/90031619-6ddd3580-dc8b-11ea-9800-710df593105e.png)
