### ISSUE TITLE
Add Left-Margin to Top Pager

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/sitewide-search-app#78]
### Issue description
When a long term/phrase has more than one page of results, the text and the pager are too smooshed together; they need more margin between the text and the pager. This only applies to the top pager.

> **ESTIMATE** 

### What's the expected change?
- 50px left-margin on the pager until Tablet breakpoint

### What's the current functionality?
- not that much margin. It looks bad.

### What's the updated acceptance criteria?
```gherkin
```

### Additional details / screenshot
- This is how it SHOULD look:
![Screen Shot 2020-08-12 at 8 38 13 AM](https://user-images.githubusercontent.com/29731392/90026816-ce697400-dc85-11ea-9813-cd72d0feddc2.png)

**Comment by blilianyu** [comment]
Looks great to us!!
