### ISSUE TITLE
Getting horizontal scroll bar for search results page with Best Bets starting at 1024px and lower 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#81]
### Issue description
On performing search with "mantle cell lymphoma" at 1024px and lower, we get horizontal scroll bar on Chrome , FF , IE and Edge.

> **ESTIMATE** 

### Steps to reproduce the issue

1.  Perform search with  "mantle cell lymphoma". 
2. Resize the browser to 1024px.
3. Scroll all the way down.
4. The horizontal scroll bar appears.

### What's the expected result?
- The horizontal scroll bar appears on the search results page at 1024px and lower.

### What's the actual result?
-The horizontal scroll bar should NOT appear on the search results page at any breakpoint.

### Additional details / screenshot
Desktop Screenshot:
![image](https://user-images.githubusercontent.com/28455973/90044005-ff07d880-dc9a-11ea-90df-1a1642315ea7.png)

Mobile Screenshot:
![File](https://user-images.githubusercontent.com/29731392/90293841-01ad2e00-de53-11ea-8e75-88208cd39985.jpg)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by blilianyu** [comment]
I am also seeing this issue on Chrome, Firefox & Safari.

**Comment by VictoriaSunNIH** [comment]
Reopening this issue - it will be addressed post 1.1 release

**Comment by sarinapadilla** [comment]
This issue has been fixed with the Redesign MVP1 release, so closing this ticket!
