### ISSUE TITLE
Autosuggest does not work on Edge on ODE

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#83]
### Issue description
*Description of the issue*
Autosuggest does not work on Edge on the ODE. Performing search with a term for example "cancer" returns results.

> **ESTIMATE** 

### Steps to reproduce the issue

1.  Type "can" in the search input box for SWS

### What's the expected result?
- The autosuggest options should display after the user types 3 or more characters in the search box.

### What's the actual result?
- The autosuggest is not displayed.

**Comment by arcepaul** [comment]
But we confirmed this works on int-ac. This is just an issue to check when a release candidate moves up to a higher tier.

**Comment by alinai** [comment]
Looks good on ODE 377

**Comment by sarinapadilla** [comment]
This ticket has been confirmed fixed, so closing.
