### ISSUE TITLE
SWS does not work for Spanish version on IE

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/sitewide-search-app#95]
### Issue description
*Description of the issue*
SWS does not work for Spanish version on IE

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  Go to ODE 377 and perform search with "cancer"
2. The SWS results are not showing up.

### What's the expected result?
- The SWS results should be returned.

### What's the actual result?
- Only the breadcrumb shows up on SWS results page not the results

### Additional details / screenshot
 
![image](https://user-images.githubusercontent.com/28455973/90405444-bd4ba900-e071-11ea-97a4-790307df4ae0.png)

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by sarinapadilla** [comment]
This will be fixed in the cgov-digital-platform repo. Closing.
